"""Generate markdown + Plotly chart report from benchmark CSV results."""
from __future__ import annotations
import argparse
import csv
import glob
from pathlib import Path
from typing import List, Dict


def load_results(results_dir: str) -> List[Dict]:
    rows = []
    for path in glob.glob(f"{results_dir}/*.csv"):
        with open(path) as f:
            reader = csv.DictReader(f)
            for row in reader:
                # Add run metadata from filename
                fname = Path(path).stem
                fname.split("_")
                row["_file"] = fname
                rows.append(row)
    return rows


def compute_summary(rows: List[Dict]) -> List[Dict]:
    from collections import defaultdict
    import statistics
    groups = defaultdict(list)
    for row in rows:
        key = row.get("_file", "unknown")
        groups[key].append(float(row.get("total_latency_ms", 0)))

    summaries = []
    for fname, lats in groups.items():
        n = len(lats)
        s = sorted(lats)
        summaries.append({
            "run": fname,
            "n_requests": n,
            "latency_p50_ms": round(s[int(0.50 * n)], 1),
            "latency_p95_ms": round(s[int(0.95 * n)], 1),
            "latency_mean_ms": round(statistics.mean(lats), 1),
        })
    return sorted(summaries, key=lambda x: x["latency_p50_ms"])


def write_report(summaries: List[Dict], output_path: str):
    lines = [
        "# Inference Optimization Benchmark Report",
        "",
        "Auto-generated by `reporting/generate_report.py`",
        "",
        "## Results Summary",
        "",
        "| Run | N | P50 (ms) | P95 (ms) | Mean (ms) |",
        "|---|---|---|---|---|",
    ]
    for s in summaries:
        lines.append(f"| {s['run']} | {s['n_requests']} | {s['latency_p50_ms']} | {s['latency_p95_ms']} | {s['latency_mean_ms']} |")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))
    print(f"Report written to {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--results", default="./results")
    parser.add_argument("--output", default="./reporting/report.md")
    args = parser.parse_args()
    rows = load_results(args.results)
    if not rows:
        print("No CSV results found.")
    else:
        summaries = compute_summary(rows)
        write_report(summaries, args.output)
